---

- name: "[Pretask] Update apt cache"
  hosts: all
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 36000

- name: '[Pretask] Install pip'
  hosts: all
  tasks:
    - name: Install pip
      become: true
      package:
        name: python3-pip
        state: present

- name: Converge
  hosts: all
  roles:
    - role: docker
