---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: buster
    box: debian/buster64
    interfaces:
      - network_name: private_network
        auto_config: true
        ip: 172.16.100.12
        type: static
    instance_raw_config_args:
      - "vm.synced_folder '.', '/vagrant', disabled: true"
    groups:
      - anarres
lint: |
  set -e
  yamllint .
  ansible-lint --exclude roles/ --exclude molecule/ --exclude library/
  flake8 --exclude roles,molecule,library
provisioner:
  name: ansible
  options:
    become: true
    extra-vars:
      testing: true
      docker_registry_mirror: http://172.16.100.1:5000
      domain: anarres.local
scenario:
  name: default
verifier:
  name: testinfra
  options:
    sudo: true
